## String Constants
sarcastic_responses = ["Sure thing", "Absolutely", "Indubitably", "No problemo", "You got it", "Consider it done", "By all means", "Sure thing boss", "I'm on it", "On it like a car bonnet", "Right away", "Righto", "My pleasure", "Glad to help", "Of course", "My apologies, how can I serve you today My Lord", "As you command", "At your service", "Gotcha", "Yep", "Yessir", "You got it boss", "As you wish", "As you will it My Lord", "I'm all over it", "Got it covered", "Don't mention it", "It's my pleasure", "I'm here for you", "I'm all ears", "Say no more", "I got this"]

help_inversion = "Textual Inversion Keywords: \n```001glitch-core, 80s-anime-ai, anime-background-style-v2, bad_prompt_version2, minecraft-concept-art, Style-Autumn, Style-Invisible-Inc-2, Style-Lofi, style-of-marc-allante, terraria-style, trigger-studio, valorantstyle, wayne-reynolds-character```"

help_lora = "Low Rank Adpations: \n You Can Adjust the :1 from [0.0-1.0] to Change the Effect's Strength ```<lora:Lora-1990sAnimeStyle:1> <lora:Lora-Arcane:1> <lora:Lora-BOTW:1> <lora:Lora-FlatColor:1> <lora:Lora-Ghibli:1> <lora:Lora-NecoArc:1> <lora:Lora-Persona:1> <lora:Lora-SamYang:1> <lora:Lora-Synthpunk:1> <lora:Lora-Tokiame:1> <lora:Lora-Vaporwave:1> <lora:Lora-VoxMachina:1> <lora:Lora-Wanostyle:1> <lora:Lora-ZeldaCid:1>```"

status_playing = ["with my emotions", "hide-and-seek", "with fire", "hard to get", "", "it cool", "dumb", "games", "catch up", "hooky", "favorites", "fast and loose", "dirty", "minecraft", "the victim", "mind games", "second fiddle", "the long game", "the fool", "for time", "the blame game", "the odds", "it by ear", "with fate"]

status_watching = ["cat videos", "ants march", "eggs hatch", "stars twinkle", "noodles dance", "cheese age", "plants drink", "ice melt", "spiders web", "turtles sprint", "rain fall", "otters float", "sand shift", "clouds race", "rocks erode", "snails speed", "paint dry", "toast"]